import type { Metadata } from "next";
import { Manrope, Mochiy_Pop_One } from "next/font/google";
import "./globals.css";

export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-family-principal",
});

export const mochiy = Mochiy_Pop_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-family-display",
});

export const metadata: Metadata = {
  title: "Cardápio Online | Pizza Planet",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${manrope.variable} ${mochiy.variable}`}>
      <body>{children}</body>
    </html>
  );
}
